package com.saidash.jdbc.starter;

import com.saidash.jdbc.starter.util.ConnectionManager;
import org.postgresql.Driver;

import java.sql.*;

public class JdbcRunner {
    public static void main(String[] args) throws SQLException {

        String sql = """
               INSERT INTO info (data)
               VALUES 
               ('autogenerated')  
                """;

        try (var connection = ConnectionManager.open();
             var statement = connection.createStatement()) {
            System.out.println(connection.getTransactionIsolation());

            System.out.println(connection.getSchema());


            var executeResult = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            var generatedKeys = statement.getGeneratedKeys();
            if(generatedKeys.next()){
                var generatedId = generatedKeys.getInt("id");
                System.out.println(generatedId);
            }


        }
    }
}

